name: Build

on: [push]

jobs:
  buildOpus:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabi, arm-unknown-linux-gnueabi, x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-cache-${{ matrix.target }}"
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --manifest-path opus-cp/rust/Cargo.toml --target ${{ matrix.target }}
      - name: Info
        run: ls -r opus-cp/${{ matrix.target }}/
  buildClient:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: chmod +x gradlew
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build mod jar
      run: ./gradlew client:deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: client/build/libs/        
